-- 1. Structured search
SELECT document_id, title, department
FROM rag.documents
WHERE department = 'Finance';

-- 2. Metadata filtering
SELECT chunk_id, document_id, content
FROM rag.document_chunks
WHERE metadata->>'access_level' = 'internal'
  AND metadata->>'region' IN ('Global', 'India');

-- 3. Vector similarity search
-- Replace the query vector with an embedding generated by the real embedding model.
SELECT
    chunk_id,
    document_id,
    content,
    1 - (embedding <=> '[0.20,0.10,0.40,0.30,0.60,0.50,0.80,0.70]') AS similarity
FROM rag.document_chunks
ORDER BY embedding <=> '[0.20,0.10,0.40,0.30,0.60,0.50,0.80,0.70]'
LIMIT 5;

-- 4. Metadata-filtered vector retrieval
SELECT
    chunk_id,
    document_id,
    content,
    1 - (embedding <=> '[0.90,0.80,0.70,0.60,0.50,0.40,0.30,0.20]') AS similarity
FROM rag.document_chunks
WHERE metadata->>'access_level' = 'internal'
ORDER BY embedding <=> '[0.90,0.80,0.70,0.60,0.50,0.40,0.30,0.20]'
LIMIT 5;

-- 5. Simple lexical + semantic candidate retrieval
SELECT
    chunk_id,
    content,
    1 - (embedding <=> '[0.90,0.80,0.70,0.60,0.50,0.40,0.30,0.20]') AS vector_similarity
FROM rag.document_chunks
WHERE content ILIKE '%AADSTS500011%'
ORDER BY embedding <=> '[0.90,0.80,0.70,0.60,0.50,0.40,0.30,0.20]'
LIMIT 5;
