import asyncio


class ModelSimulator:

    def __init__(self):
        self.failure_mode = "normal"
        self.call_count = 0

    def set_failure_mode(self, mode: str):
        self.failure_mode = mode
        self.call_count = 0

    async def call(self, model_name: str):

        self.call_count += 1

        await asyncio.sleep(0.1)

        # Normal operation
        if self.failure_mode == "normal":
            return {
                "success": True,
                "model": model_name,
                "response": f"Response generated by {model_name}",
            }

        # First two calls fail, then recover
        if self.failure_mode == "transient_failure":

            if self.call_count <= 2:
                raise TimeoutError(
                    f"{model_name} temporarily unavailable"
                )

            return {
                "success": True,
                "model": model_name,
                "response": f"Recovered response from {model_name}",
            }

        # Every call fails
        if self.failure_mode == "persistent_failure":
            raise TimeoutError(
                f"{model_name} persistently unavailable"
            )

        # Primary model is unavailable
        if self.failure_mode == "primary_model_down":

            if model_name == "primary-model":
                raise ConnectionError(
                    "Primary model unavailable"
                )

            return {
                "success": True,
                "model": model_name,
                "response": f"Fallback response from {model_name}",
            }

        # Region failure
        if self.failure_mode == "region_down":
            raise ConnectionError(
                "Region unavailable"
            )

        return {
            "success": True,
            "model": model_name,
            "response": f"Response generated by {model_name}",
        }